<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="TechCirle2sMini" name="SaturdayPractice.dependsOnSaturdayReview" tests="9" failures="1" timestamp="2022-05-21T13:27:45 EDT" time="0.020" errors="0">
  <testcase name="test3" time="0.000" classname="SaturdayPractice.dependsOnSaturdayReview">
    <skipped/>
  </testcase> <!-- test3 -->
  <system-out/>
  <testcase name="test" time="0.000" classname="SaturdayPractice.dependsOnSaturdayReview">
    <skipped/>
  </testcase> <!-- test -->
  <system-out/>
  <testcase name="test1" time="0.000" classname="SaturdayPractice.dependsOnSaturdayReview">
    <skipped/>
  </testcase> <!-- test1 -->
  <system-out/>
  <testcase name="test6" time="0.002" classname="SaturdayPractice.dependsOnSaturdayReview">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at SaturdayPractice.dependsOnSaturdayReview.test6(dependsOnSaturdayReview.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test6 -->
  <system-out/>
  <testcase name="test7" time="0.002" classname="SaturdayPractice.dependsOnSaturdayReview"/>
  <system-out/>
  <testcase name="test5" time="0.002" classname="SaturdayPractice.dependsOnSaturdayReview"/>
  <system-out/>
  <testcase name="test2" time="0.000" classname="SaturdayPractice.dependsOnSaturdayReview">
    <skipped/>
  </testcase> <!-- test2 -->
  <system-out/>
  <testcase name="test0" time="0.014" classname="SaturdayPractice.dependsOnSaturdayReview"/>
  <system-out/>
  <testcase name="test4" time="0.000" classname="SaturdayPractice.dependsOnSaturdayReview">
    <skipped/>
  </testcase> <!-- test4 -->
  <system-out/>
</testsuite> <!-- SaturdayPractice.dependsOnSaturdayReview -->
